name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Silverblue Image'
            run: |
              podman build -f Containerfile --tag ghcr.io/larnhow/fedora-bootc:42-silverblue --build-arg=FEDORA_DE=silverblue
              podman push ghcr.io/larnhow/fedora-bootc:42-silverblue



